### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mortonjt** [mortonjt/differential#1]
- [x] Incorporate basic differential abundance methods (DESeq2, CLR, possibly ALDEX2)
- [ ] Create command line scripts
- [ ] Create HTML reports
- [ ] ChatGPT generated reports??
